---
- name: Pull the docker/distribution git repository
  git:
    repo: "https://github.com/docker/distribution.git"
    dest: "{{ registry_gopath }}/src/github.com/docker/distribution"
    version: "{{ registry_version }}"
  register: __registry_repository

- name: Build the docker registry binary
  shell: "make build && make binaries"
  args:
    chdir: "{{ registry_gopath }}/src/github.com/docker/distribution"
  environment:
    GOPATH: "{{ registry_gopath }}"
    GOROOT: "{{ registry_golang_install_dir }}"
    PATH: "{{ ansible_env.PATH }}:{{ registry_golang_install_dir }}/bin"
  when: __registry_repository | changed
